name: Deploy API to Render

on:
  workflow_dispatch:
  push:
    branches: [ "master" ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.13.4'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pytest

      # - name: Run unit tests
#         run: |
#           pytest deliverables/api/tests/

      - name: Trigger Render Deployment
        if: success()
        run: |
          curl -X POST ${{ secrets.RENDER_DEPLOY_HOOK_URL }}
